// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: grpc/database/proto/bills-database.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_database_proto_bills_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_database_proto_bills_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_grpc_database_proto_bills_database_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Bills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	DueDate string `protobuf:"bytes,4,opt,name=Due_date,json=DueDate,proto3" json:"Due_date,omitempty"`
}

func (x *Bills) Reset() {
	*x = Bills{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_database_proto_bills_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bills) ProtoMessage() {}

func (x *Bills) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_database_proto_bills_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bills.ProtoReflect.Descriptor instead.
func (*Bills) Descriptor() ([]byte, []int) {
	return file_grpc_database_proto_bills_database_proto_rawDescGZIP(), []int{1}
}

func (x *Bills) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Bills) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bills) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Bills) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

var File_grpc_database_proto_bills_database_proto protoreflect.FileDescriptor

var file_grpc_database_proto_bills_database_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x2d, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x06, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x5c, 0x0a, 0x05, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x44, 0x75, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x75, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x32, 0x51, 0x0a, 0x14, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x67, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69,
	0x6c, 0x6c, 0x73, 0x22, 0x00, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x47, 0x61, 0x62, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x2d,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x42, 0x69,
	0x6c, 0x6c, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_database_proto_bills_database_proto_rawDescOnce sync.Once
	file_grpc_database_proto_bills_database_proto_rawDescData = file_grpc_database_proto_bills_database_proto_rawDesc
)

func file_grpc_database_proto_bills_database_proto_rawDescGZIP() []byte {
	file_grpc_database_proto_bills_database_proto_rawDescOnce.Do(func() {
		file_grpc_database_proto_bills_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_database_proto_bills_database_proto_rawDescData)
	})
	return file_grpc_database_proto_bills_database_proto_rawDescData
}

var file_grpc_database_proto_bills_database_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_database_proto_bills_database_proto_goTypes = []interface{}{
	(*Client)(nil), // 0: database_proto.Client
	(*Bills)(nil),  // 1: database_proto.Bills
}
var file_grpc_database_proto_bills_database_proto_depIdxs = []int32{
	0, // 0: database_proto.BillsDatabaseService.getAll:input_type -> database_proto.Client
	1, // 1: database_proto.BillsDatabaseService.getAll:output_type -> database_proto.Bills
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_database_proto_bills_database_proto_init() }
func file_grpc_database_proto_bills_database_proto_init() {
	if File_grpc_database_proto_bills_database_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_database_proto_bills_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_database_proto_bills_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bills); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_database_proto_bills_database_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_database_proto_bills_database_proto_goTypes,
		DependencyIndexes: file_grpc_database_proto_bills_database_proto_depIdxs,
		MessageInfos:      file_grpc_database_proto_bills_database_proto_msgTypes,
	}.Build()
	File_grpc_database_proto_bills_database_proto = out.File
	file_grpc_database_proto_bills_database_proto_rawDesc = nil
	file_grpc_database_proto_bills_database_proto_goTypes = nil
	file_grpc_database_proto_bills_database_proto_depIdxs = nil
}
