// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: grpc/database/bills-database.proto

package Bills_apigateway_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillsDatabaseClient is the client API for BillsDatabase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillsDatabaseClient interface {
	GetAll(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Bills, error)
}

type billsDatabaseClient struct {
	cc grpc.ClientConnInterface
}

func NewBillsDatabaseClient(cc grpc.ClientConnInterface) BillsDatabaseClient {
	return &billsDatabaseClient{cc}
}

func (c *billsDatabaseClient) GetAll(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Bills, error) {
	out := new(Bills)
	err := c.cc.Invoke(ctx, "/BillsDatabase/getAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillsDatabaseServer is the server API for BillsDatabase service.
// All implementations must embed UnimplementedBillsDatabaseServer
// for forward compatibility
type BillsDatabaseServer interface {
	GetAll(context.Context, *Client) (*Bills, error)
	mustEmbedUnimplementedBillsDatabaseServer()
}

// UnimplementedBillsDatabaseServer must be embedded to have forward compatible implementations.
type UnimplementedBillsDatabaseServer struct {
}

func (UnimplementedBillsDatabaseServer) GetAll(context.Context, *Client) (*Bills, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBillsDatabaseServer) mustEmbedUnimplementedBillsDatabaseServer() {}

// UnsafeBillsDatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillsDatabaseServer will
// result in compilation errors.
type UnsafeBillsDatabaseServer interface {
	mustEmbedUnimplementedBillsDatabaseServer()
}

func RegisterBillsDatabaseServer(s grpc.ServiceRegistrar, srv BillsDatabaseServer) {
	s.RegisterService(&BillsDatabase_ServiceDesc, srv)
}

func _BillsDatabase_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillsDatabaseServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BillsDatabase/getAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillsDatabaseServer).GetAll(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

// BillsDatabase_ServiceDesc is the grpc.ServiceDesc for BillsDatabase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillsDatabase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BillsDatabase",
	HandlerType: (*BillsDatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAll",
			Handler:    _BillsDatabase_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/database/bills-database.proto",
}
